language: node_js
node_js:
    - 'lts/*'
cache:
    directories:
        - ~/.npm
install: npm install
jobs:
    include:
        - stage: lint
          script: npm run lint
        - stage: test
          script: npm run test
        - stage: build
          script: npm run build
branches:
    only: master
notifications:
    email: false
