language: node_js
node_js:
    - 'node'
    - 'lts/*'
cache:
    directories:
        - ~/.npm
install: npm install
script:
    - npm run lint
    - npm run test
    - npm run build
branches:
    only: master
notifications:
    email: false
